-- #1
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- #2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- #1
SHOW TRANSACTION ISOLATION LEVEL;
-- #2
SHOW TRANSACTION ISOLATION LEVEL;
-- #1
SELECT SUM(rating) FROM pizzeria;
-- #2
UPDATE pizzeria SET rating = 5 WHERE name = 'Pizza Hut';
COMMIT;
-- #1
SELECT SUM(rating) FROM pizzeria;
COMMIT;
SELECT SUM(rating) FROM pizzeria;
-- #2
SELECT SUM(rating) FROM pizzeria;