-- #1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- #2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- #1
SHOW TRANSACTION ISOLATION LEVEL;
-- #2
SHOW TRANSACTION ISOLATION LEVEL;
-- #1
UPDATE pizzeria SET rating = 4.5 WHERE id = 1;
-- #2
UPDATE pizzeria SET rating = 4.9 WHERE id = 2;
-- #1
UPDATE pizzeria SET rating = 4.5 WHERE id = 2;
-- #2
UPDATE pizzeria SET rating = 4.9 WHERE id = 1;
-- #1
COMMIT;
-- #2
COMMIT;
-- #1
SELECT * FROM pizzeria;
-- #2
SELECT * FROM pizzeria;
